"""Updated user

Revision ID: 0f3267219977
Revises: 0b8838420a55
Create Date: 2026-02-04 03:10:02.711126+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3267219977'
down_revision: Union[str, Sequence[str], None] = '0b8838420a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('is_superuser', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('display_name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_users_display_name'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_display_name'), ['display_name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_display_name'))
        batch_op.create_unique_constraint(batch_op.f('uq_users_display_name'), ['display_name'])
        batch_op.alter_column('display_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_superuser')
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###
